# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'qomeq' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for qomeq
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  target 'qomeqTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'qomeqUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
